<?php

/**
 *  Implements hook_menu().
 */
function render_examples_menu() {
  $items = array();

  $items['render-examples/example1'] = array(
    'title' => 'Demo page 1',
    'page callback' => 'render_examples_example1',
    'file' => 'render_examples.pages.inc',
    'access callback' => TRUE,
  );

  return $items;
}


/**
 *  Implements hook_theme().
 */
function render_examples_theme($existing, $type, $theme, $path) {
  $themes = array();

  $themes['user_achievements'] = array(
    'path' => drupal_get_path('module', 'render_examples') . '/templates',
    'template' => 'user-achievements',
    'variables' => array(
      'points' => '',
      'score' => '',
    ),
  );

  $themes['render_add_span'] = array(
    'file' => 'render_examples.theme.inc',
    'render element' => 'element',
  );

  return $themes;
}

/**
 * Custom pre_render callback for caching example.
 * @param $element
 * @return mixed
 */
function render_element_cached_pre_render($element) {
  $element['#markup'] = render_elements_expensive();
  $element['#children'] = $element['#markup'];
  return $element;
}

/**
 * Custom function that retrieve a string after a while.
 * @see render_element_cached_pre_render
 * @return string
 */
function render_elements_expensive() {
  sleep(5);
  return t('Have you waited a lot? Sorry, it won\'t happen for 10 seconds');
}