<?php

/**
 *  Implements hook_menu().
 */
function render_examples_menu() {
  $items = array();

  $items['render-examples/example1'] = array(
    'title' => 'Demo page 1',
    'page callback' => 'render_examples_example1',
    'file' => 'render_examples.pages.inc',
    'access callback' => TRUE,
  );

  return $items;
}


/**
 *  Implements hook_theme().
 */
function render_examples_theme($existing, $type, $theme, $path) {
  $themes = array();

  $themes['user_achievements'] = array(
    'path' => drupal_get_path('module', 'render_examples') . '/templates',
    'template' => 'user-achievements',
    'variables' => array(
      'points' => '',
      'score' => '',
    ),
  );

  return $themes;
}